### ISSUE TITLE
No project / post title when sharing on G+

### ISSUE THREAD

**Issue by claudiobgit** [toybreaker/binocle#1]
When you +1 a specific project you don't get the title of the project in the post (on Facebook everything works fine).
![binocle-googleplus-sharing-ss](https://cloud.githubusercontent.com/assets/20387258/16716276/054e5206-46f8-11e6-8592-b4039acbacbc.JPG)

**Comment by toybreaker** [comment]
fixed with [schema.org micro data](https://developers.google.com/web/fundamentals/discovery-and-monetization/social-discovery/?hl=en#use-schemaorg--microdata-to-provide-rich-snippets-on-google)

<img width="430" alt="screen shot 2016-07-11 at 15 35 07" src="https://cloud.githubusercontent.com/assets/8560097/16732414/51ae795c-477d-11e6-980a-4b670bdae445.png">

<img width="468" alt="screen shot 2016-07-11 at 15 39 53" src="https://cloud.githubusercontent.com/assets/8560097/16732503/dc964b44-477d-11e6-84cd-d6203de1e786.png">
